config/routes.rb
Rails.application.routes.draw do

  resources :friendships

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
    resources :users, only: [:show, :index, :destroy]

  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'legal', to: 'pages#legal'
  get 'contact', to: 'pages#contact'
  get 'formation', to: 'pages#formation'
  get 'start', to: 'pages#start'
  get 'profile', to: 'pages#profile'

  root to: 'pages#home'

  resources :posts do
      resources :comments
  end

  resources :favs, only: [:index, :destroy]

  post 'favs/:post_id', to: 'favs#create', as: "post_favs"
  get 'favs', to: 'favs#index'
  delete 'favs/:post_id', to: 'favs#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :favs, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  # after_create :subscribe_to_newsletter

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

#private

  # def subscribe_to_newsletter
  #   SubscribeToNewsletter.new(self).run
  # end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
 def facebook
  user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

if user.persisted?
  sign_in_and_redirect user, event: :authentication
  set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
else
  session['devise.facebook_data'] = request.env['omniauth.auth']
  redirect_to new_user_registration_url
end
end

# # if user.persisted? #&& user.#city.blank?
# #    redirect_to #
# #else


  # def google
  #   user = User.find_for_google_oauth(request.env['omniauth.auth'])

  #   if user.persisted?
  #     sign_in_and_redirect user, event: :authentication
  #     set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
  #   else
  #     session['devise.google_data'] = request.env['omniauth.auth']
  #     redirect_to new_user_registration_url
  #   end
  # end

  # def google_oauth2
  #   user = User.find_for_google_oauth2(request.env['omniauth.auth'])

  #   if user.persisted?
  #     sign_in_and_redirect user, event: :authentication
  #     set_flash_message(:notice, :success, kind: 'GoogleOauth2') if is_navigational_format?
  #   else
  #     session['devise.google_oauth2_data'] = request.env['omniauth.auth']
  #     redirect_to new_user_registration_url
  #   end
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :city, :email, :password, :password_confirmation, :picture)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :picture, :city, :email, :password, :password_confirmation, :biography, :website, :social_link1, :social_link2, :social_link3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, except: [:index]
  #before_action :find_user, only: [:show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :picture)

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container-buddies">
  <div class="container-fluid">
    <div class="row">
      <div class= "col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 form-buddy ">
        <div class="form-bg1 form-three ">
          <table class="table table-striped table-hover table-users text-center">
              <thead >
                <tr>
                  <th>
                    <p class="text-center">Buddies</p>
                  </th>
                  <th>
                    <p class="text-center">Name</p>
                  </th>
                  <th>
                    <p class="text-center">Follow</p>
                  </th>
                </tr>
              </thead>
              <tbody>
                <% @users.each do |user| %>
                <tr>
                  <td>
                    <%= link_to user_path(user) do %>
                    <%= image_tag user.picture || "http://api.adorable.io/avatars/300/#{user.email}" %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to user_path(user) do %>
                    <%= user.first_name %> <%= user.last_name[0] %>.
                    <% end %>
                  </td>
                  <td>
                    <% if current_user.id == user.id %>
                      <p>Hey</p>
                    <% else %>
                      <%= link_to "Add as Friend", friendships_path(:friend_id => user), :method => :post %>
                    <% end %>
                    <!-- link_to "Supprimer des favs", fav_path(fav), method: :delete -->
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-login">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4">
        <div class="form-login">
          <div class=" form-bg form-one text-center">
            <div class="text-center">
              <% if current_user.id == @user.id %>
                <p>Hey</p>
              <% else %>
                <%= link_to "Add Me as Friend", friendships_path(:friend_id => @user), :method => :post, class: "btn btn-default" %>
              <% end %>
            </div>

            <h4>Ma Room </h4>
        <!-- Notification -->
            <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
            <div class="badge-container">
              <i class="fa fa-envelope-o"></i>
              <div class="badge badge-blue">3</div>
            </div>
            <% end %>








          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="form-login">
          <div class=" form-bg form-one text-center">
            <%= image_tag @user.picture || "http://api.adorable.io/avatars/300/#{current_user.email}", class: "user-picture" %>
          <div id="name-profile">
            <h1 class="text-center">
              <% if @user.first_name.blank? %>
                <strong>C'est quoi ton nom ?</strong>
              <% else %>
                <%= @user.first_name.capitalize %> <%=@user.last_name.capitalize[0] %>.
              <% end %>
            </h1>
          </div>
            <ul class="list-unstyled list-inline text-center">
              <li>
                <% if @user.social_link1.blank? %>
                <% else %>
                <%= link_to @user.social_link1, target: "_blank" do %>
                  <i class="fa fa-twitter fa-lg"></i>
                <% end %>
                <% end %>
              </li>
              <li>
                <% if @user.social_link2.blank? %>
                <% else %>
                <%= link_to @user.social_link2, target: "_blank" do %>
                <i class="fa fa-facebook-square fa-lg"></i>
                <% end %>
                <% end %>
              </li>
              <li>
                <% if @user.social_link3.blank? %>
                <% else %>
                <%= link_to @user.social_link3, target: "_blank" do %>
                  <i class="fa fa-linkedin fa-lg"></i>
                  <% end %>
                <% end %>
              </li>
            </ul>
              <% if @user.website.blank? %>
                <p>J'ai toujours pas de site web :)</p>
                  <% else %>
                <%= link_to @user.website, target: "_blank"  %>
              <% end %>

            <% if  @user == current_user %>

            <% if @user.social_link1.blank? %>
            <h5>
              <%= link_to t(".top_call_to_action", default: "Je crée mon profil"), edit_user_registration_path, class: "btn btn-default text-center mini-space" %>
            </h5>
            <% else %>
              <h5>
                <%= link_to t(".top_call_to_action", default: "J'ajoute encore des infos !"), edit_user_registration_path, class: "btn btn-default text-center second-button" %>
              </h5>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-login">
        <div class="form-bg form-one text-center">
          <div class="tiny-space">
            <h4>
              Mes buddies
            </h4>
          </div>
            <ul class="list-unstyled" >
              <% @user.friendships.each do |friendship| %>
                <li class="col-sm-6 col-sm-3 col-md-3 col-md-offset">
                  <div class="friend-picture">
                    <%= link_to user_path(friendship.friend) do %>
                      <%= h image_tag friendship.friend.picture || "http://api.adorable.io/avatars/300/#{friendship.friend.email}" %>
                    <% end %>
                  </div>
                  <h6>
                    <%= link_to user_path(friendship.friend) do %>
                      <%=h friendship.friend.first_name %> <%=h friendship.friend.last_name[0] %>
                    <% end %>
                    <%= link_to friendship, :method => :delete do %>
                      <i class="fa fa-times fa-lg"></i>
                    <% end %>
                  </h6>
                </li>
              <% end %>
            </ul>
            <% if @user == current_user %>
              <div class="text-center">
                <h5><%= link_to "Find Buddies", users_path, class: "btn btn-default mini-space friends-button" %></h5>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>