config/routes.rb
Rails.application.routes.draw do

  resources :friendships

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
    resources :users, only: [:show, :index, :destroy]

  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'legal', to: 'pages#legal'
  get 'contact', to: 'pages#contact'
  get 'formation', to: 'pages#formation'
  get 'start', to: 'pages#start'
  get 'profile', to: 'pages#profile'

  root to: 'pages#home'

  resources :posts do
      resources :comments
  end

  resources :favs, only: [:index, :destroy]

  post 'favs/:post_id', to: 'favs#create', as: "post_favs"
  get 'favs', to: 'favs#index'
  delete 'favs/:post_id', to: 'favs#destroy'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :post

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/fav.rb
class Fav < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :categories, dependent: :destroy
  has_many :favs, dependent: :destroy
  has_many :comments, dependent: :destroy

  TAGS = ["Design", "Mode", "Tendance", "Life-Style", "Tradition", "Gastronomie", "Insolite", "Technologie"]

  validates :tag, inclusion: { in: Post::TAGS, allow_nil: false }
  validates :user_id, presence: true
  validates :content, presence: true

  mount_uploader :cover, ImageUploader

  include PgSearch
  pg_search_scope :search,
    against: [ :title, :content, :tag ],
    associated_against: {
      categories: [:name]
    }

  def is_faved_by(user)
    self.favs.where(user: user).take
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :favs, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  # after_create :subscribe_to_newsletter

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

#private

  # def subscribe_to_newsletter
  #   SubscribeToNewsletter.new(self).run
  # end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_post, only: [:show, :new, :create, :destroy]

  def show
    @category = Category.find(params[:id])
  end

  def index
    @categories = Category.all
  end

  def create
    @category = @post.categories.new(category_params)
    if @category.save
      redirect_to @post
    else
      render 'categories/show'
    end
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def update

  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to post_path(@post)
  end

  private


  def set_post
    @post = Post.find(params[:post_id])
  end

  def category_params
    params.require(:category).permit(:name, :description, :post_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "You commented the hell out of that post!"
      redirect_to :back
    else
      flash[:notice] = "Check the comment form, something went horribly wrong."
      render root_path
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    flash[:notice] = "Comment deleted :("
    redirect_to :back
  end

private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end
end

app/controllers/favs_controller.rb
class FavsController < ApplicationController
 def index
    @favs = Fav.where(user: current_user)
  end

  def create
    @post = Post.find(params[:post_id])
    @fav = current_user.favs.where(post: @post).first
    if @fav.present?
      @fav.destroy
    else
      @fav = current_user.favs.new(post: @post)
      if not @post.favs.where(user: current_user).take
        @fav.save
      end
    end
    # redirect_to favs_path
    # redirect_to :back
    respond_to do |format|
      format.js { render :ajax_update_favs }
    end
  end

  def destroy
    @fav = Fav.find(params[:id])
    @fav.destroy
    redirect_to :back
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def start
  end

  def contact
  end

  def legal
  end

  def profile
  end

  def formation
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
    if params[:search] and not params[:search][:query].blank?
      @posts = @posts.search params[:search][:query]
    end
  end

  def show
    # @alert_message = "Vous lisez #{@post.title}"
  end

  def new
    # if current_user and current_user.admin?
      @post = Post.new
    # else
    #   redirect_to posts_path
    # end
  end

  def create
    # if current_user and current_user.admin?
      @post = current_user.posts.new(post_params)
      if @post.save
        redirect_to @post
      else
        render :new
      end
    # else
    #   render 'shared/404.html.erb'
    # end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to :back
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :introduction, :content, :cover, :tag)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, except: [:index]
  #before_action :find_user, only: [:show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :picture)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(content)
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, space_after_headers: true, fenced_code_blocks: true)
    @markdown.render(content).html_safe
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favs_helper.rb
module FavsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bosser en pyjama</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">

     <!-- Markdown -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
  </head>

  <body>
    <!-- simple markdown -->
    <script src="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

    <%= render 'shared/navbar' %>
    <div class="flashes">
      <%= render 'shared/flashes' %>
    </div>
    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>


  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/formation.html.erb
<h1>Pages#formation</h1>
<p>Find me in app/views/pages/formation.html.erb</p>

app/views/pages/home.html.erb
<div class="coverhome">
  <div class="coverhome-filter">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="separator">
            <h1>
              Crééz votre site web
            </h1>
          </div>
          <ul class="list-unstyled list-inline">
            <li>
              <%= link_to start_path do %>
              <div class="btn btn-default btn-top">
                <h5>Je commence</h5>
              </div>
            <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class=" cover-slide-two ">
  <div class="coverhome-filter-one">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">

          <h1>RECEVEZ MES DERNIERES NEWS</h1>

            <div class="btn btn-default btn-mid" data-toggle="modal" data-target=".bs-example-modal-lg">
              <h5>Click click click</h5>
              </div>


  <!-- Large modal -->
           <!--  <button type="button" class="btn btn-default btn-mid" data-toggle="modal" data-target=".bs-example-modal-lg">Large modal</button> -->

            <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
              <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <!-- Begin MailChimp Signup Form -->

              <style type="text/css">
                #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
                /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
                   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
              </style>
              <div id="mc_embed_signup">
              <form action="//bosserenpyjama.us13.list-manage.com/subscribe/post?u=058b809fbb841077f7b13c6c2&amp;id=1ba4b0fa24" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                  <div id="mc_embed_signup_scroll">
                <h3 class="text-center">Inscris-toi à la Newsletter</h3>
              <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
              <div class="mc-field-group">
                <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
              </label>
                <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
              </div>
              <div class="mc-field-group">
                <label for="mce-FNAME">First Name </label>
                <input type="text" value="" name="FNAME" class="" id="mce-FNAME">
              </div>
              <div class="mc-field-group">
                <label for="mce-LNAME">Last Name </label>
                <input type="text" value="" name="LNAME" class="" id="mce-LNAME">
              </div>
                <div id="mce-responses" class="clear">
                  <div class="response" id="mce-error-response" style="display:none"></div>
                  <div class="response" id="mce-success-response" style="display:none"></div>
                </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                  <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_058b809fbb841077f7b13c6c2_1ba4b0fa24" tabindex="-1" value=""></div>
                  <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
                  </div>
              </form>
              </div>
              <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
              <!--End mc_embed_signup-->
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="cover-slide-three">
  <div class="coverhome-filter-one">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <h1>Une sélection de sites </h1>
              <h2>Qui va vraiment vous aider !</h2>
            <div class="training-section">
              <%= link_to "En savoir plus", "#", class:'subscribe-button subscribe-training', target: '_blank' %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<!-- <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="recipient-name" class="control-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>
 -->

app/views/pages/legal.html.erb
<h1>Pages#legal</h1>
<p>Find me in app/views/pages/legal.html.erb</p>

app/views/pages/profile.html.erb
<div class="container-login">
  <div class="container-fluid">
    <div class="row">
      <div class= "col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 form-login ">
        <div class="form-bg form-one text-center">
          <div class="profile-picture">
            <%= image_tag current_user.picture || "http://api.adorable.io/avatars/300/#{current_user.email}" %>
          </div>
            <div id="name-profile">
              <h1 class="text-center">
                <% if @user.first_name.blank? %>
                <strong>C'est quoi ton nom ?</strong>
                <% else %>
                <%= @user.first_name.capitalize %> <%=@user.last_name.capitalize[0] %>
                <% end %>
              </h1>
            </div>
        <ul class="list-unstyled list-inline text-center">
          <li>
            <% if @user.social_link1.blank? %>
            <% else %>
            <%= link_to @user.social_link1, target: "_blank" do %>
            <i class="fa fa-twitter fa-lg"></i>
            <% end %>
            <% end %>
          </li>
          <li>
            <% if @user.social_link2.blank? %>
            <% else %>
            <%= link_to @user.social_link2, target: "_blank" do %>
            <i class="fa fa-facebook-square fa-lg"></i>
            <% end %>
            <% end %>
          </li>
          <li>
            <% if @user.social_link3.blank? %>
            <% else %>
            <%= link_to @user.social_link3, target: "_blank" do %>
            <i class="fa fa-linkedin fa-lg"></i>
            <% end %>
            <% end %>
          </li>
        </ul>
        <% if @user.social_link1.blank? %>
        <%= link_to t(".top_call_to_action", default: "Je créé mon profil comme un chef"), edit_user_registration_path, class: "navbar-wagon-item navbar-wagon-button btn text-center" %>
        <% else %>
          <%= link_to t(".top_call_to_action", default: "Modifier mon profil"), edit_user_registration_path, class: "navbar-wagon-item navbar-wagon-button btn text-center" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/start.html.erb
Hello

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible disapearUp" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice.html_safe %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible disapearUp" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert.html_safe %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container-fluid">
    <div class="row">

         <div class="col-xs-12 col-sm-3 col-md-3">
          <ul class="list-unstyled list-footer">
              <li class="list-title">
                <%= link_to legal_path do %>
                  <p>Mentions légales</p>
              </li>
              <% end %>
          </ul>
        </div>

        <div class="col-xs-12 col-sm-3 col-md-3">
          <ul class="list-unstyled list-footer">
              <li class="list-title">
                <%= link_to contact_path do %>
                  <p>Contactez-moi</p>
              </li>
              <% end %>
          </ul>
        </div>

        <div class="col-xs-12 col-sm-3 col-md-3">
          <ul class="list-unstyled list-footer">
              <li class="list-title">
                <%= link_to about_path do %>
                  <p>Qui je suis !</p>
              </li>
              <% end %>
          </ul>
        </div>

        <div class="col-xs-12 col-sm-3 col-md-3">
          <ul class="list-unstyled list-inline list-footer">
              <li class="list-title">
                <a href="https://www.facebook.com/bosserenpyj" target="_blank">
                  <i class="fa fa-facebook-official fa-2x"></i>
                </a>
              </li>
              <li>
                <a href="https://twitter.com/bosserenpyj" target="_blank">
                  <i class="fa fa-twitter fa-2x"></i>
                </a>
            </li>
             <li>
              <a href="#" >
                <i class="fa fa-youtube fa-2x"></i>
              </a>
            </li>
          </ul>
        </div>
    </div>

        <div class="line-separator col-xs-12 col-sm-4 col-sm-offset-4"></div>
        <div class="copyright row text-center" id="footer-heart">
            <p>Créé avec <span class="display-3 text-xs-center mt animated bounceInDown text-center"><%= icon('heart', class: "text-danger animated pulse infinite") %></span> sous la couette</p>
        </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-logo" do %>
    <%= image_tag "logo-bosser-en-pyjama.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right "> <!-- hidden-xs hidden-sm -->

    <%= link_to t(".top_call_to_action", default: "BLOG"), posts_path, class: "blog-style" %>

    <!-- Search form -->
   <!--  <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.picture || "http://api.adorable.io/avatars/300/#{current_user.email}", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Mon Profil" %>
              <% end %>
            </li>
            <li>
              <%= link_to favs_path do %>
                <i class="fa fa-heart"></i> <%= t ".profile", default: "Mes articles favoris" %>
              <% end %>
            </li>
            <li>
               <%= link_to edit_user_registration_path do %>
                <i class="fa fa-pencil-square-o"></i> <%= t ".profile", default: "Editer mon profil" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Je me lance"), start_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
<!--   <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div> -->
</div>