config/routes.rb
Rails.application.routes.draw do

  resources :friendships

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
    resources :users, only: [:show, :index, :destroy]

  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'legal', to: 'pages#legal'
  get 'contact', to: 'pages#contact'
  get 'formation', to: 'pages#formation'
  get 'start', to: 'pages#start'
  get 'profile', to: 'pages#profile'

  root to: 'pages#home'

  resources :posts do
      resources :comments
  end

  resources :favs, only: [:index, :destroy]

  post 'favs/:post_id', to: 'favs#create', as: "post_favs"
  get 'favs', to: 'favs#index'
  delete 'favs/:post_id', to: 'favs#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :categories, dependent: :destroy
  has_many :favs, dependent: :destroy
  has_many :comments, dependent: :destroy

  TAGS = ["Design", "Mode", "Tendance", "Life-Style", "Tradition", "Gastronomie", "Insolite", "Technologie"]

  validates :tag, inclusion: { in: Post::TAGS, allow_nil: false }
  validates :user_id, presence: true
  validates :content, presence: true

  mount_uploader :cover, ImageUploader

  include PgSearch
  pg_search_scope :search,
    against: [ :title, :content, :tag ],
    associated_against: {
      categories: [:name]
    }

  def is_faved_by(user)
    self.favs.where(user: user).take
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
    if params[:search] and not params[:search][:query].blank?
      @posts = @posts.search params[:search][:query]
    end
  end

  def show
    # @alert_message = "Vous lisez #{@post.title}"
  end

  def new
    # if current_user and current_user.admin?
      @post = Post.new
    # else
    #   redirect_to posts_path
    # end
  end

  def create
    # if current_user and current_user.admin?
      @post = current_user.posts.new(post_params)
      if @post.save
        redirect_to @post
      else
        render :new
      end
    # else
    #   render 'shared/404.html.erb'
    # end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to :back
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :introduction, :content, :cover, :tag)

  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<div class="row">
  <div class= "col-md-8 col-md-offset-2">
      <%= simple_form_for [@post, @post.comments.new] do |f| %>
        <%= f.error_notification %>
        <%= f.input :content, label: "Commentaire"%>
        <%= f.submit "Envoyer", class: "btn btn-default" %>
      <% end %>
  </div>
</div>

app/views/posts/_form.html.erb
<div class="row">
  <div class= "col-md-8 col-md-offset-2 form-post">
    <h3 class="text-center">Créer/Modifier un article</h3>
      <%= simple_form_for @post do |f| %>
      <%= f.error_notification %>
      <%= f.input :title, label: 'Title', input_html: { class: "input-lg"} %>
      <%= f.input :tag, collection: Post::TAGS, selected: Post::TAGS.first %>
    <div class="row">
      <div class="col-sm-6">
        <%= f.input :cover %>
      </div>
    </div>
      <%= f.input :introduction, label: 'Introduction', input_html: { rows: 5} %>
      <%= f.input :content, label: 'Body', placeholder: "Tapez ici votre article", input_html: { rows: 5, id: "post_content"} %>
    <div class="text-center">
      <%= f.submit "Publier l'article maintenant", class: "btn btn-danger btn-lg" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_postuser.html.erb
<div class="card-filter-home" style="background: url(<%= cloudinary_url post.cover %>); background-size:cover">
  </div>

  <div class="card-details">

    <% if current_user.try(:admin?) %>
      <%= link_to post_path(post), class:'trash-article', data: { confirm: 'Are you sure?' }, method: :delete do %>
      <%= image_tag("delete-btn.png") %>
      <% end %>
    <% end %>

    <%= link_to post_path(post) do %>

    <span class="card-post-tag card-post-tag-<%= post.tag.downcase %>"><%= post.tag %></span>
    <h4><%= post.title %></h4>

   <h6 class="card-post-author">
      posté par Baptiste
    </h6>

    <div id="favorite_<%=post.id %>">
      <%= render 'favs/favorites', post: post %>
    </div>

    <% end %>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<div class="container-formpost">
  <div class="container-fluid ">

      <%= render 'form' %>

  </div>
</div>

app/views/posts/index.html.erb
<div class="container-formpost">
  <div id="home-articles">
    <div class="container">
      <div class="text-center separ-blog">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <div class="search-form">
              <%= simple_form_for :search, url: posts_path, method: :get, :html => { :class => 'form-inline' } do |f| %>
              <%= f.input :query, label: false, placeholder: "" %>
              <%= f.submit "Rechercher",  class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
        </div>
        <h1>Lisez mes derniers articles</h1>
        <ul>
          <% @posts.each do |post| %>
          <li class=" col-sm-12 col-xs-6 col-md-4 container-cards">
            <%= render 'postuser', post: post %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container-formpost">
  <div class="container-fluid ">
    <% if current_user.try(:admin?) %>
      <%= render 'form' %>
    <%end%>
  </div>
</div>

app/views/posts/show.html.erb
<div id="show-post">
  <div class="container-post">
    <div class ="headline headline-<%= @post.tag.downcase %>">
      <%= @post.title %>
    </div>
    <div class="container-fluid">
      <div class="row">
        <div class="text-center ">
        </div>
          <%= cl_image_tag @post.cover, :crop => :fill, class: "img-post-header" %>
          <div class="col-md-8 col-md-offset-2">
            <div class="article">
              <div class="tags tags-<%= @post.tag.downcase %>">
                <%= @post.tag %>
              </div>
              <div class="category-tab">
                <% @post.categories.each do |category| %>
                  <%= category.name %>
                <% end %>
              </div>
              <div class="intro-part">
                <h5>
                  <strong>
                    <%= @post.introduction %>
                  </strong>
                </h5>
              <div class="content-part">
                <p><%= markdown @post.content %></p>
              </div>


              <div class="comments-part">
                <ul class="list-unstyled">
                  <% @post.comments.each do |comment| %>
                  <li>

                    <h6><%= image_tag comment.user.picture || "http://api.adorable.io/avatars/300/#{comment.user.email}", class: "user-picture" %> <%= comment.user.first_name %> <%= comment.user.last_name[0] %>. </h6>
                    <p><%= comment.content %></p>
                  </li>
                  <% if comment.user == current_user  %>
                    <%= link_to post_comment_path(post_id: @post.id, id: comment.id), method: :delete, data: { confirm: "Are you sure?" } do %>
                      <i class="fa fa-trash"></i>
                    <% end %>
                  <% end %>
                  <% end %>
                </ul>
                  <%= render 'comments' %>
              </div>

              <div class="text-center buttons-view-post">
              <% if current_user.try(:admin?) %>
                <%= link_to "Modifier l'article", edit_post_path(@post), class: "btn btn-default btn-md" %>
                <%= link_to "Créer un article", new_post_path, class: "btn btn-default btn-md" %>
                <%= link_to "Voir tous les articles", posts_path, class: "btn btn-default btn-md" %>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>